services:

  app:
    container_name: oop-basics-extras-2
    build:
      dockerfile: Dockerfile
      target: development
      args:
        - BUILDKIT_INLINE_CACHE=0
    user: vscode
    volumes:
      - .:/workspace
    entrypoint: [ "/usr/local/bin/entrypoint.sh" ]
    command: [ "tail", "-f", "/dev/null" ]
